### ISSUE TITLE
Windows issue with "ffmpeg" file in PATH

### ISSUE THREAD

**Issue by Damitrix** [tomaszzmuda/Xabe.FFmpeg#223]
Having a file called "ffmpeg" (no extension) in your Windows PATH before the "ffmpeg.exe" will lead to an
`System.ComponentModel.Win32Exception: 'The specified executable is not a valid application for this OS platform.'`
exception when trying to run Conversion.Start().

Renaming it allowed the program to find the actual ffmpeg.exe
Normal command line works with this setup, so I think it's a valid problem.

_I set my PATH to the folder where the media autobuild suite created all files, that's why there was such a file in the first place_

```
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Xabe.FFmpeg.FFmpeg.RunProcess(String args, String processPath, Nullable`1 priority, Boolean standardInput, Boolean standardOutput, Boolean standardError)
   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_0.<RunProcess>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Xabe.FFmpeg.Conversion.<Start>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoCompressor.Program.<MainAsync>d__10.MoveNext() in C:\Users\Chris\source\repos\VideoCompressor\VideoCompressor\Program.cs:line 95
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VideoCompressor.Program.<Main>d__8.MoveNext() in C:\Users\someone\source\repos\VideoCompressor\VideoCompressor\Program.cs:line 15
```

**Comment by tomaszzmuda** [comment]
I'm going to handle that. Give me few days :)

**Comment by tomaszzmuda** [comment]
Unfortunately, I cannot reproduce this issue. In 4 of my PCs everything works fine. Anyone else having this problem too?

**Comment by 06needhamt** [comment]
I cannot reproduce this issue either on either of my 2 development machines both running the latest build of Windows 10 x64.

Winver screenshot for reference,

![image](https://user-images.githubusercontent.com/4162227/75612384-c627dd00-5b1a-11ea-8068-79924f2ab111.png)
