### ISSUE TITLE
Help with "Custom" Concatenating .ts files

### ISSUE THREAD

**Issue by NinDTendo** [tomaszzmuda/Xabe.FFmpeg#285]
I am trying to pass the concat protocol command from [ffmpeg docs](https://trac.ffmpeg.org/wiki/Concatenate#protocol)  to  Xabe.FFmpeg with `Conversion.Start(string)` according to the [Docs](https://ffmpeg.xabe.net/joining_videos.html), but I am getting a  ` Invalid argument` exception thrown

According to the [ffmpeg docs](https://trac.ffmpeg.org/wiki/Concatenate#protocol) the command to concatenating the files using "Concat protocol" is:  `ffmpeg -i "concat:input1.ts|input2.ts|input3.ts" -c copy output.ts`
My command string (customConcatCommand) is as follows:
```
ffmpeg -i "concat:'D:\Userdata\Videos\Test\57961393\temp\57961393-0.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-1.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-2.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-3.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-4.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-5.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-6.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-7.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-8.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-9.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-10.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-11.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-12.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-13.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-14.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-15.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-16.ts'" -c copy 'D:\Userdata\Videos\Test\57961393\57961393.ts'
```
which is used in 
```
await conversion.Start(customConcatCommand);
```

I think my command is wrong, so it would be very helpful if someone could point iut, what is wrong, or how it should be formatted/formulated.

This is the exception:
```
Unhandled exception. Xabe.FFmpeg.Exceptions.ConversionException: ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.101 / 58.101.101
  libavformat    58. 51.101 / 58. 51.101
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
concat:'D:\Userdata\Videos\Test\57961393\temp\57961393-0.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-1.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-2.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-3.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-4.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-5.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-6.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-7.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-8.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-9.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-10.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-11.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-12.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-13.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-14.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-15.ts'|'D:\Userdata\Videos\Test\57961393\temp\57961393-16.ts': Invalid argument
   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_0.<RunProcess>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Xabe.FFmpeg.Conversion.Start(String parameters, CancellationToken cancellationToken)
   at VideoDownloader.Program.MainAsync(String[] args) in D:\Userdata\Documents\GitHub\VideoDownloader\Program.cs:line 168
   at VideoDownloader.Program.Main(String[] args) in D:\Userdata\Documents\GitHub\VideoDownloader\Program.cs:line 22

```

**Comment by tomaszzmuda** [comment]
Hi @NinDTendo,

We had a lot of problems with implementing the concatenation of videos. Current solution is more generic so it should work. If you need better speed try use concat with external file - https://superuser.com/questions/718027/ffmpeg-concat-doesnt-work-with-absolute-path

If you are trying to pass your own arguments be sure that works in FFmpeg. Sometimes the arguments are very complicated and can work differently on Windows or Linux so I suggest you to use build in snippet for that.

And if you want to use **Start(string)** method remove "ffmpeg" from the beginning.
