### ISSUE TITLE
Error while extracting frames from video

### ISSUE THREAD

**Issue by h-c-a** [tomaszzmuda/Xabe.FFmpeg#328]
Hi super thanks for a fantastic library!

using it for extracting images from videos.

here is my method

```
var conversion = FFmpeg.Conversions.New()
         .AddParameter($"-i {momentFile}")
         .AddParameter("-vf select='if(not(floor(mod(t,6)))*lt(ld(1),1),st(1,1)+st(2,n)+st(3,t));if(eq(ld(1),1)*lt(n,ld(2)+1),1,if(trunc(t-ld(3)),st(1,0)))'")
         .AddParameter("-vsync 0")
         .SetOutput($"{Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly()?.Location), $"{_uploadFolder}/{momentId}/images/%4d.jpg")}");

 conversion.OnProgress += async (sender, args) =>
  {
      var percent = (int) (Math.Round(args.Duration.TotalSeconds / args.TotalLength.TotalSeconds, 2) * 100);
  
      _logger.Information($"Image extraction args: {JsonConvert.SerializeObject(args)}" ); 
      
      _logger.Information($"Image extraction percent {percent}" ); 

      if (percent != 100) return;
  };
          
```
also tried

```
                var info = await FFmpeg.GetMediaInfo(momentFile);
                var videoStream = info.VideoStreams.First().SetCodec(VideoCodec.png);

                string OutputBuilder(string number) => Path.Combine($"{Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly()?.Location), $"{_uploadFolder}/{momentId}/images/")}", number + ".png");

                var conversion = FFmpeg.Conversions.New()
                    .AddStream(videoStream)
                    .ExtractEveryNthFrame(10, OutputBuilder);


```

however i get an error:

```

at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_1.<RunProcess>b__2()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
--- End of inner exception stack trace ---
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.TimerQueue.FireNextTimers()
---> (Inner Exception #0) System.IO.IOException: Broken pipe
at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
at System.IO.FileStream.CheckFileCall(Int32 result, Boolean ignoreNotSupported)
at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
at System.IO.FileStream.FlushWriteBuffer()
at System.IO.FileStream.Flush(Boolean flushToDisk)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.WriteSpan(ReadOnlySpan`1 buffer, Boolean appendNewLine)
at System.IO.StreamWriter.Write(String value)
at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_1.<RunProcess>b__2()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<---

```

**Comment by h-c-a** [comment]
sample file used for conversion

https://user-images.githubusercontent.com/1141897/106324593-b7413180-6279-11eb-8dad-d55ccb7faec4.mp4

**Comment by tomaszzmuda** [comment]
Hey,

I cannot reproduce that issue, on my PC your code works well. Only one case when it doesn't work is when the output directory does not exist. But in that case, I don't get any errors - just nothing there in the output folder (it definitely has to be done soon).

You can catch that exception as ConversionException and check Message and InnerException.
Also, you can try to create output directory by your own first.

P.S. Which version of Xabe.FFmpeg do you use?
