### ISSUE TITLE
Error: "String '' was not recognized as a valid TimeSpan" when converting certain video files

### ISSUE THREAD

**Issue by milankarman** [tomaszzmuda/Xabe.FFmpeg#358]
When trying to convert certain videos to an image sequence I get a "String '' was not recognized as a valid TimeSpan." error thrown, yet the ffmpeg process starts and eventually finishes anyway.

These my arguments:
```           
        IConversion conversion = FFmpeg.Conversions.New()
                .AddStream(videoStream)
                .ExtractEveryNthFrame(1, outputFileNameBuilder);
                .AddParameter("-q:v 3");
```

I get the following error:
```
System.FormatException
  HResult=0x80131537
  Message=String '' was not recognized as a valid TimeSpan.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetBadTimeSpanFailure()
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.TimeSpan.Parse(String s)
   at Xabe.FFmpeg.FFmpegWrapper.GetDuration(DataReceivedEventArgs e, Regex regex, String args)
   at Xabe.FFmpeg.FFmpegWrapper.CalculateTime(DataReceivedEventArgs e, String args, Int32 processId)
   at Xabe.FFmpeg.FFmpegWrapper.ProcessOutputData(DataReceivedEventArgs e, String args, Int32 processId)
   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_1.<RunProcess>b__1(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```
    
 And here's the output when running ffprobe on one of the video files in question:
 ```
 Input #0, matroska,webm, from '.\The Hobbit (GCN) Speedrun in 26_12 (Any% NMG)-nb_CcNjCP5k.mkv':
  Metadata:
    HTTP://YOUTUBE.COM/STREAMING/OTF/DURATIONS/112015: Segment-Count: 384
                    : Segment-Durations-Ms: 5067,5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),5066,5067(r=1),506
                    :
                    :
    ENCODER         : Lavf58.65.101
  Duration: 00:32:25.97, start: 0.000000, bitrate: 2024 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      DURATION        : 00:32:25.899000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:32:25.971000000`
```
 Any clue if this is a mistake on my side or a bug the library?

**Comment by tomaszzmuda** [comment]
Hi,
I tried to process that media (I've found it on youtube) but everything works for me.
Can you:
- Share a bit more of your code (from creating of new conversion to call start method)
- Share exact media that cause issue
- Tell me on what operting system do you get that issue

**Comment by milankarman** [comment]
Thanks for your response, here's more of my code

```cs
        // Outputs a video file as images of every individual frame in the specified directory
        public static async Task<IConversionResult> ConvertToImageSequence(string inputPath, string outputPath, CancellationTokenSource cts, Action<double> onProgress)
        {
            // Names every image file as their frame number
            string outputFileNameBuilder(string _)
            {
                return Path.Join(outputPath, "%d.jpg");
            }

            // Reads in the video file and configures to resize it
            IMediaInfo info = await FFmpeg.GetMediaInfo(inputPath).ConfigureAwait(false);
            IVideoStream videoStream = info.VideoStreams.First()?.SetSize(640, 360);

            // Prepares for converting every video frame to an image
            IConversion conversion = FFmpeg.Conversions.New()
                .AddStream(videoStream)
                .ExtractEveryNthFrame(1, outputFileNameBuilder)
                .AddParameter("-q:v 3");

            // Notifies the calling location on the progress of converting
            conversion.OnProgress += (sender, args) =>
            {
                double percent = Math.Round(args.Duration.TotalSeconds / args.TotalLength.TotalSeconds * 100, 2);
                onProgress(percent);
            };

            // Starts and awaits the convertion while giving it a cancellation token so it can be stopped at will
            return await conversion.Start(cts.Token);
        }
```

I've uploaded the exact video file I'm having trouble with here: https://drive.google.com/file/d/1jRNDcdI9XTf-0njyraz-6Pu9HGN95h-P/view?usp=sharing
This is just a YouTube video downloaded with youtube-dl

I'm using 64bit Windows 10 Home version 20H2 and release version 4.4 of FFMpeg.

Thanks for looking into it 😀

**Comment by tomaszzmuda** [comment]
I found the bug.
#359 
It should be pushed to nuget tomorrow :)
Thanks for help

**Comment by milankarman** [comment]
Thanks for the fix!

**Comment by tomaszzmuda** [comment]
It took less time than I thought :)
It would be great if you can confirm if in newest version (5.0.1) everything works

**Comment by milankarman** [comment]
Just got the chance to try it, seems to work perfectly. Thanks again for the quick fix!
