### ISSUE TITLE
Unhandled exception when ffmpeg process disappears 

### ISSUE THREAD

**Issue by broderickhyman** [tomaszzmuda/Xabe.FFmpeg#361]
I don't know the root cause of why my ffmpeg process is disappearing but I haven't been able to catch the exception that gets thrown when it does. This causes our Scheduler software to crash which is not ideal.
I don't mind an exception being thrown when it can't be found, but I would like to be able to catch it and handle it.
@tomaszzmuda If necessary I could make the code changes, but some general direction would be helpful if it is not a quick change.
Stacktrace:
```
Unhandled Exception: System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_1.<RunProcess>b__1(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by tomaszzmuda** [comment]
Hello @broderickhyman 
I wasn't able to reproduce that issue but I believe that I've found an issue.
Could you please use code from #362?
If you have problems with the source I can release it as a preview version.

**Comment by broderickhyman** [comment]
Thanks! I was able to build it and have been testing it for a day or two, so far it looks to have solved the issue! I will check back in next week with confirmation.
