### ISSUE TITLE
UnauthorizedAccessException on Android, how to download ffmpeg onto Android device?

### ISSUE THREAD

**Issue by techmaticsnz** [tomaszzmuda/Xabe.FFmpeg#385]
I haven't been able to find a site for just queries how to use the program, so here I am.
If there is a site for general queries about program can you please direct me to it?

That said, here's what i'm experiencing:

```2021-10-06 12:11:16.579 9651-9651/com.techmaticsnz.herelinkvideo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.techmaticsnz.herelinkvideo, PID: 9651
    android.runtime.JavaProxyThrowable: System.UnauthorizedAccessException: Access to the path '/storage/emulated/0/ffmpeg/ffmpeg' is denied. ---> System.IO.IOException: Operation not permitted
       --- End of inner exception stack trace ---
      at Interop.ThrowExceptionForIoErrno (Interop+ErrorInfo errorInfo, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00014] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at Interop.CheckIo (System.Int64 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x0000a] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at Interop.CheckIo (System.Int32 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00000] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at System.IO.FileStatus.SetAccessWriteTimes (System.String path, System.Nullable`1[T] accessSec, System.Nullable`1[T] accessUSec, System.Nullable`1[T] writeSec, System.Nullable`1[T] writeUSec) [0x000cb] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at System.IO.FileStatus.SetLastWriteTime (System.String path, System.DateTimeOffset time) [0x00041] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at System.IO.FileSystemInfo.set_LastWriteTimeCore (System.DateTimeOffset value) [0x00000] in <c72658f647bc485bbfb8c9fcaa790862>:0 
        at (wrapper remoting-invoke-with-check) System.IO.FileSystemInfo.set_LastWriteTimeCore(System.DateTimeOffset)
      at System.IO.FileSystem.SetLastWriteTime (System.String fullPath, System.DateTimeOffset time, System.Boolean asDirectory) [0x00017] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) [0x0000c] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at System.IO.Compression.ZipFileExtensions.ExtractToFile (System.IO.Compression.ZipArchiveEntry source, System.String destinationFileName, System.Boolean overwrite) [0x00067] in <661e85c6446a4f58848e4d83697216dd>:0 
      at Xabe.FFmpeg.Downloader.FFmpegDownloaderBase.Extract (System.String ffMpegZipPath, System.String destinationDir) [0x00053] in <633dbaed4d894a3abcbe989e0e8dbaf8>:0 
      at Xabe.FFmpeg.Downloader.Android.AndroidFFmpegDownloader.GetLatestVersionForArchitecture (System.String path, Xabe.FFmpeg.Downloader.OperatingSystemArchitecture arch, System.IProgress`1[T] progress, System.Int32 retries) [0x0009a] in <633dbaed4d894a3abcbe989e0e8dbaf8>:0 
      at Xabe.FFmpeg.Downloader.Android.AndroidFFmpegDownloader.GetLatestVersion (System.String path, System.IProgress`1[T] progress, System.Int32 retries) [0x00081] in <633dbaed4d894a3abcbe989e0e8dbaf8>:0 
      at Xabe.FFmpeg.Downloader.FFmpegDownloader.GetLatestVersion (Xabe.FFmpeg.Downloader.FFmpegVersion version, System.String path, System.IProgress`1[T] progress) [0x000b2] in <633dbaed4d894a3abcbe989e0e8dbaf8>:0 
      at HereLinkVideo.Video.LoadFFmpegAndStartRecording () [0x0009a] in <b79bfd96d71f49f6b891bea2e8b76e81>:0 
      at HereLinkVideo.Video.OnRecordClicked (System.Object sender, System.EventArgs args) [0x000fa] in <b79bfd96d71f49f6b891bea2e8b76e81>:0 
      at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <c72658f647bc485bbfb8c9fcaa790862>:0 
      at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <1410c4afb1fd4823a12ecf897dd92287>:0 
      at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <1410c4afb1fd4823a12ecf897dd92287>:0 
      at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <1410c4afb1fd4823a12ecf897dd92287>:0 
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.25(intptr,intptr)
        at mono.java.lang.RunnableImplementor.n_run(Native Method)
        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
```

The code i have to load this is:
```
string ffmpeg = @"/storage/emulated/0/ffmpeg";
FFmpeg.SetExecutablesPath(ffmpeg);
await FFmpegDownloader.GetLatestVersion(FFmpegVersion.Android, ffmpeg);
```

I've given android the storage permission, And it seems that it doesn't get past downloading the program. I have made a folder in /storage/emulated/0/ffmpeg for where the files should be located.
I did this just by connecting my device to my computer and doing usb files transfer option, i can confirm that the ffmpeg folder is in the internal storage.
Testing this i opened the folder and ffmpeg and ffprobe are not located in this folder. My expected result is that i can connect the device by usb and see ffmpeg and ffprobe programs in the /storage/emulated/0/ffmpeg folder.

**Comment by tomaszzmuda** [comment]
Hello,

Sometimes downloaded executables didn't get executable permission on Android.
Can you check that?
