### ISSUE TITLE
Getting Stackoverflow on long conversions

### ISSUE THREAD

**Issue by JPVenson** [tomaszzmuda/Xabe.FFmpeg#427]
Hey, i am currently converting some audio files that can take some time and one of them brought the wrapper to crash the whole application:

```
System.OverflowException: The TimeSpan string '25:56:36' could not be parsed because at least one of the numeric components is out of range or contains too many digits.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetOverflowFailure()
   at System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at Xabe.FFmpeg.FFmpegWrapper.GetDuration(DataReceivedEventArgs e, Regex regex, String args)
   at Xabe.FFmpeg.FFmpegWrapper.CalculateTime(DataReceivedEventArgs e, String args, Int32 processId)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

```
using System.Globalization;
. 
. CultureInfo.CurrentCulture
[en-DE]
```

**Comment by tomaszzmuda** [comment]
Hello @JPVenson 
Can you show me the exact arguments that are passed to FFmpeg?
Or which methods do you use to build conversion. Do you use "-t" or "-ss"?

**Comment by JPVenson** [comment]
Hey @tomaszzmuda, Its a bit hard to reproduce now as I moved to another FFmpeg Wrapper. From my commit history I can only say that this happend on the `FFmpeg.GetMediaInfo` call. Also i had random crashes with the GetMediaInfo in a parallel execution scenario, that was why i tried a retry pattern.

My code was like this:
```csharp
IMediaInfo mediaInfo = null;
await Policy.Handle<Exception>()
	.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(1))
	.ExecuteAsync(async () =>
	{
		mediaInfo = await FFmpeg.GetMediaInfo(currentItem);
	});


var conversion = FFmpeg.Conversions.New()
	.AddStream(mediaInfo.Streams)
	.AddParameter($"-activation_bytes {Passkey}", ParameterPosition.PreInput)
	.SetOutputFormat(Format.mp3)
	.SetOutput(Path.Combine(OutputDir, workingFileName));

```

**Comment by tomaszzmuda** [comment]
I'm going to investigate problem with GetMediaInfo. Thanks for you code.
